### ISSUE TITLE
Mapping Question

### ISSUE THREAD

**Issue by bassman2112** [optimistex/xlsx-template-ex#11]
Hi there,

let's say my json data is as such:

```
{
	"testing": [
		{
			"test": "hey I worked"
                }
          ]
}
```

I'm trying to template this out on a sheet to grab "test," but nothing I'm doing is working.

I've tried.

`{{test}}`
`{{testing.test}}`
`{{testing|test}}`
`{{testing|get:test}}`

and nothing is working.

I also tried the test data and using `{{results|find:text:some text 2|get:answerText}}` and that also isn't working on the an xlsx template using the example data. Is something weird with the templating? Is it a mistake I'm making?

Thank you =]

**Comment by optimistex** [comment]
@bassman2112 
Example:

```typescript
let data ={
	"testing": [
		{"test": "hey one pass"},
		{"test": "hey two fail"},
		{"test": "hey three pass"},
          ]
};
```
**!!!** In the example / used instead of | because of a trouble with the markdown syntax

| A     |
|-------|
| [[testing/repeat-rows:1]] {{test}} |

Received result:

| A     |
|-------|
| hey one pass |
| hey two fail |
| hey three pass |
