### ISSUE TITLE
{{propertyName1}}{{propertyName2}} in the same cell

### ISSUE THREAD

**Issue by yannis-a** [optimistex/xlsx-template-ex#17]
When I put two properties in the same cell, like this |   from {{propertyName1}} to {{propertyName2}}  |  <- this is a cell 
the module understands and takes the value of the second only. Is it normal for the module to act this way?
Thank you !
ps: sorry for my english: s

**Comment by optimistex** [comment]
@yannis-a Do not sorry for your English, it's my native also )))

Generally, it's expected to have one template per cell. If you added a pull request with the new logic, I'd review and release it.
