### ISSUE TITLE
Cannot read property 'my_property' of null (Use dot notation)

### ISSUE THREAD

**Issue by RBN1993** [optimistex/xlsx-template-ex#20]
Hi,

First of all, thank for your library. It's awesome!

I've tried to make my own template to generate an excel but when I write something like 'data.otherProperty' it throws an error like "Cannot read 'otherProperty' property of null" when 'data' does not exist. I prefer access to data with dot notation and maybe it could be more comfortable
I overwrite your code and this let me generate an excel without errors: 
`
// In your /app/node_modules/xlsx-template-ex/dist/app/template-engine.js file

const R = require('ramda') // or lodash
........
    processTplValues(tplExp, data) {
        // if (!resultData) {
        //     resultData = tplExp.valueName.split(".").reduce((o, key) => ((o && o[key]) || o[key] === 0 ? o[key] : null), this.data);
        // }
        return R.pathOr('',tplExp.valueName.split('.'),data);
    }
`

Maybe you have to implement it in other cases like pipes. And if you could add nested arrays access with dot notation...

I hope you could add this change and make a release to download.

Thank you!

**Comment by optimistex** [comment]
@RBN1993 

Hello! Check examples with custom pipes:
https://github.com/optimistex/xlsx-template-ex/blob/cb57afaed602cb075af4a25600f34199e6b98a0a/src/example.ts#L285-L286
https://github.com/optimistex/xlsx-template-ex/blob/cb57afaed602cb075af4a25600f34199e6b98a0a/src/example.ts#L312-L318
![image](https://user-images.githubusercontent.com/11228640/111195744-4190eb00-85c5-11eb-9d6b-2c891a9748e7.png)
![image](https://user-images.githubusercontent.com/11228640/111195843-58cfd880-85c5-11eb-9bce-f0ad6262fa6e.png)

Most probably you could add your own pipe that reads nested properties by your own rules.

Also, I highly recommend to prepare/simplify your data before render. For instance, when you need to render a deeply nested property it's a sign that you have not so well prepared data. Process it before render. My main idea to keep the template engine as simple as it possible and ensure Excel things like insert a picture or clone cells, but not to invent a data engine. For processing data you already have NodeJs. So, use NodeJs to bring your complex data set to some simple representation that is ready to be rendered into an Excel.
