### ISSUE TITLE
How mapping array in array

### ISSUE THREAD

**Issue by ddivitay** [optimistex/xlsx-template-ex#21]
I have:
`array1 = [
   {
     id: 1,
     array2: [{ text: 1 }, { text: 2 }, { text: 3 }]
   }
   ....
]`

Please help me (

I need print all array2 items where id = 1

**Comment by optimistex** [comment]
@ddivitay 
Let's assume that you have:
```typescript
let data = {
    array1: [
        { id: '1', label: 'item 1', array2: [{ text: 11 }, { text: 21 }, { text: 31 }] },
        { id: '2', label: 'item 2', array2: [{ text: 12 }, { text: 22 }, { text: 32 }] },
        { id: '1', label: 'item 3', array2: [{ text: 110 }, { text: 210 }, { text: 310 }] },
        { id: '3', label: 'item 4', array2: [{ text: 13 }, { text: 23 }, { text: 33 }] },
    ],
};
```
then expected formula could be:
- A1 >> `[[array1\|filter:id:1\|repeat-rows:2]]{{label}}`
- A2 >> `[[array2\|repeat-rows:1]]{{text}}`

And the result:

 A |  B
-- | --
item 1 |  
11 |  
21 |  
31 |  
item 3 |  
110 |  
210 |  
310 |  

![image](https://user-images.githubusercontent.com/11228640/111194227-a3e8ec00-85c3-11eb-8625-c7f678025879.png)
![image](https://user-images.githubusercontent.com/11228640/111194190-99c6ed80-85c3-11eb-98df-a8f2892db7cf.png)

**Pay attention:**
- I changed the id values from numbers to strings! There is an issue in `filter` pipe with numbers 
- I highly recommend simplifying data structures before render
